### 여러 개의 테이블을 세로로 결합하기
SELECT 'APP1' AS APP_NAME, USER_ID, NAME, EMAIL FROM APP1_MST_USERS
UNION ALL
SELECT 'APP2' AS APP_NAME, USER_ID, NAME, NULL AS EMAIL FROM APP2_MST_USERS;

/*
* UNION ALL 사용 시에는 컬럼이 동일해야함.
* 컬럼이 다를 경우, 기본값을 지정해서 사용 가능
*/

### 여러 개의 테이블을 가로로 정렬하기
-- 잘못된 경우
SELECT 
	M.CATEGORY_ID
    , M.NAME
    , S.SALES
    , R.PRODUCT_ID AS SALE_PRODUCTS
FROM MST_CATEGORIES AS M
LEFT JOIN CATEGORY_SALES AS S
ON M.CATEGORY_ID = S.CATEGORY_ID
LEFT JOIN PRODUCT_SALE_RANKING AS R
ON M.CATEGORY_ID = R.CATEGORY_ID;

### 마스터 테이블 행 수를 변경하지 않고 여러 개의 테이블을 가로로 정렬하는 쿼리
SELECT 
	M.CATEGORY_ID
    , M.NAME
    , S.SALES
    , R.PRODUCT_ID AS TOP_SALE_PRODUCT
FROM MST_CATEGORIES AS M
LEFT JOIN CATEGORY_SALES AS S
ON M.CATEGORY_ID = S.CATEGORY_ID
LEFT JOIN PRODUCT_SALE_RANKING AS R
ON M.CATEGORY_ID = R.CATEGORY_ID
AND R.RANKING = 1;

### 상관 서브쿼리로 여러 테이블을 가로로 정렬 - 이 부분 안 됨
SELECT 
M.CATEGORY_ID
, M.NAME
, (SELECT S.SALES
	FROM CATEGORY_SALES AS S
    WHERE S.CATEGORY_ID = M.CATEGORY_ID) AS SALES
, (SELECT R.PRODUCT_ID
	FROM PRODUCT_SALE_RANKING AS R
    WHERE R.CATEGORY_ID = M.CATEGORY_ID)
FROM MST_CATEGORIES AS M
